Repository openimsdk/openim-docker, pull requests merged in 2024-01, with the labels that each got.

#61 fix: fix Security vulnerability
  .github/sync.yml
  .github/workflows/openimci.yml
  .github/workflows/sync.yml
  .gitignore
  example/.env
  example/basic-openim-server-dependency.yml
  example/full-openim-server-and-chat.yml
  example/host-network-basic-openim-server-dependency.yml
  example/only-openim-server.yml
  example/only-openim-web.yml
  example/volume-all-server.yml
  scripts/init-config.sh
Labels: size/XXL

#74 Feat/add openim docker ci fix
  README.md
  README_zh-CN.md
Labels: size/XL

#75 Update .env.example
  .env.example
Labels: size/S

#79 Update README.md
  README.md
Labels: size/XS

#80 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#81 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/S

#86 fix: docker compose up failed because of mysql config lack platform arm
  docker-compose.yaml
Labels: size/XS

#88 feat: add openim mongo logic
  .env.example
  .github/workflows/openimci.yml
  example/basic-openim-server-dependency.yml
  example/full-openim-server-and-chat.yml
  example/full-openim-server-chat-web-admin.yml
  example/full-openim-server-chat-web.yml
  example/only-openim-server.yml
  example/volume-all-server.yml
  scripts/mongo-init.sh
Labels: size/M

#90 feat: add go formity checker
  openim-chat/README.md
  openim-server/README.md
Labels: size/XS

#91 feat: add instance down rules yaml file
  docker-compose.yaml
Labels: size/XS

#101 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#102 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#103 Update docker-compose.yaml
  .env.example
  docker-compose.yaml
Labels: size/XS

#105 Update docker-compose.yaml support arm/v6, arm/v8
  docker-compose.yaml
Labels: size/XS

#108 Update .gitignore
  .gitignore
Labels: size/XS

#109 Update .env.example
  .env.example
Labels: size/XS

#111 feat: supoort openim-chat source code deployment in mac
  .env.example
  FAQ-CN.md
  docker-compose.yaml
  example/basic-openim-server-dependency.yml
  example/full-openim-server-and-chat.yml
  example/full-openim-server-chat-web-admin.yml
  example/full-openim-server-chat-web.yml
  example/only-openim-server.yml
  example/volume-all-server.yml
Labels: size/M
